"""Empirical Challenger Test Suite for Milestone 2 (R1: Full Localization & Clean Presentation).

Adversarially tests HTML, CSV, and PDF representations generated by snapshot_renderer
and snapshot_exports against the forbidden token specification:
r'\\b(?:REQUIREMENT_|APPLICATION:|SEARCH_IN|SEARCH_EX|handbook:\\d|primary:\\d|target:\\d|WAIVER_DECISION_REQUIRED|RULE_CONTEXT:MANUAL_REVIEW|CREDIT_CONSERVATION_FAILED|attempt:\\d)\\b'
"""

from __future__ import annotations

import csv
import io
import re
import unittest
from dataclasses import replace
from decimal import Decimal
from typing import Any

import fitz

from allocation_engine import (
    COMPLETE,
    VERIFIED,
    AllocationResult,
    AttemptAllocation,
    CourseAttempt,
    CreditPortion,
    RequirementResult,
    RequirementSpec,
)
from decision_snapshot import DecisionSnapshot, build_decision_snapshot
from snapshot_exports import (
    build_student_allocation_csv,
    build_student_pdf,
)
from snapshot_renderer import (
    build_snapshot_projection,
    clean_student_facing_text,
    format_handbook_citation,
    render_snapshot,
    translate_requirement_blocker,
)


FORBIDDEN_TOKEN_REGEX = re.compile(
    r"\b(?:REQUIREMENT_|APPLICATION:|SEARCH_IN|SEARCH_EX|handbook:\d|primary:\d|target:\d|WAIVER_DECISION_REQUIRED|RULE_CONTEXT:MANUAL_REVIEW|CREDIT_CONSERVATION_FAILED|attempt:\d)\b"
)


def _extract_pdf_text(pdf_bytes: bytes) -> str:
    """Extract plain text from PDF bytes using PyMuPDF."""
    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    text = "\n".join(page.get_text() for page in doc)
    doc.close()
    return text


def _extract_csv_rows_and_text(csv_bytes: bytes) -> tuple[list[dict[str, str]], str]:
    """Decode UTF-8 BOM CSV bytes and return parsed rows and raw text."""
    csv_text = csv_bytes.decode("utf-8-sig")
    reader = csv.DictReader(io.StringIO(csv_text))
    return list(reader), csv_text


def _build_adversarial_snapshot(
    *,
    blockers: tuple[str, ...] = (),
    warnings: tuple[str, ...] = (),
    remediation_suggestions: tuple[str, ...] = (),
    rule_provenance: tuple[dict[str, Any], ...] = (),
    decisions: dict[str, Any] | None = None,
    non_credit_results: tuple[dict[str, Any], ...] = (),
    subset_results: tuple[dict[str, Any], ...] = (),
    requirement_results: tuple[RequirementResult, ...] = (),
    requirements: tuple[RequirementSpec, ...] = (),
    attempts: tuple[CourseAttempt, ...] = (),
    allocations: tuple[AttemptAllocation, ...] = (),
) -> DecisionSnapshot:
    """Construct a synthetic, highly hostile DecisionSnapshot for adversarial testing."""
    default_attempts = attempts or (
        CourseAttempt("attempt:113-1:MATH101:0", "MATH101", "微積分(一)", Decimal("3"), Decimal("3"), "113-1", status="PASS"),
        CourseAttempt("attempt:114-1:CHEM101:0", "CHEM101", "普通化學", Decimal("3"), Decimal("0"), "114-1", status="IN_PROGRESS"),
    )
    default_requirements = requirements or (
        RequirementSpec(
            "primary:113:earth:domain-elective",
            "地生系專業選修",
            Decimal("6"),
            eligible_course_ids=("MATH101",),
            coverage_state=COMPLETE,
            evidence_state=VERIFIED,
            bucket="elective",
            kind="選修",
        ),
        RequirementSpec(
            "target:115:apc:chemistry:compulsory",
            "物化系化學組必修",
            Decimal("4"),
            eligible_course_ids=("CHEM101",),
            coverage_state="PARTIAL",
            evidence_state=VERIFIED,
            bucket="required",
            kind="必修",
        ),
    )
    default_req_results = requirement_results or (
        RequirementResult("primary:113:earth:domain-elective", "UNKNOWN", Decimal("6"), Decimal("3"), Decimal("0"), Decimal("3"), Decimal("3"), "COMPLETE", "VERIFIED", blockers=("REQUIREMENT_DEFICIT:primary:113:earth:domain-elective",)),
        RequirementResult("target:115:apc:chemistry:compulsory", "UNKNOWN", Decimal("4"), Decimal("0"), Decimal("0"), Decimal("0"), Decimal("4"), "PARTIAL", "VERIFIED", blockers=("REQUIREMENT_DEFICIT:target:115:apc:chemistry:compulsory",)),
    )
    default_allocations = allocations or (
        AttemptAllocation("attempt:113-1:MATH101:0", Decimal("3"), (CreditPortion("attempt:113-1:MATH101:0", "primary:113:earth:domain-elective", Decimal("3")),), Decimal("0")),
        AttemptAllocation("attempt:114-1:CHEM101:0", Decimal("0"), (), Decimal("3")),
    )

    base = build_decision_snapshot(
        {
            "attempts": default_attempts,
            "requirements": default_requirements,
            "input_confirmation": {
                "state": "CONFIRMED",
                "current_fingerprint": "adv-fixture",
                "confirmed_fingerprint": "adv-fixture",
                "formal_release_success": True,
                "row_count": len(default_attempts),
                "released_row_count": len(default_attempts),
            },
        },
        evaluated_at="2026-09-06T12:00:00Z",
    )

    allocation = AllocationResult(
        status="UNKNOWN",
        allocations=default_allocations,
        requirement_results=default_req_results,
        source_earned_credits=Decimal("3"),
        recognized_credits=Decimal("3"),
        unallocated_credits=Decimal("3"),
        credit_conservation=True,
    )

    default_decisions = decisions or {
        "primary_graduation": {"status": "UNKNOWN", "reason": "仍有要求尚未完成"},
        "double_major_qualification": {"status": "UNKNOWN", "reason": "APPLICATION:APPLICATION_FORMAL_APPROVAL_MISSING"},
        "formal_double_major_award": {"status": "UNKNOWN", "reason": "APPLICATION:DOUBLE_MAJOR_NOT_APPROVED"},
        "minor_application_or_qualification": {"status": "UNKNOWN", "reason": "APPLICATION:MINOR_NOT_APPROVED"},
        "overall": {"status": "UNKNOWN", "reason": "RULE_CONTEXT:MANUAL_REVIEW"},
    }

    return replace(
        base,
        allocation=allocation,
        snapshot_id="snapshot:adv-test-m2",
        verdict="UNKNOWN",
        decisions=default_decisions,
        rule_provenance=rule_provenance or (
            {
                "requirement_id": "primary:113:earth:domain-elective",
                "source_reference": "handbook:113:earth:primary:earth_environment:domain-elective:p45:r0",
                "source_location": "PDF p.45 專業選修表",
                "coverage_state": "COMPLETE",
                "evidence_state": "VERIFIED",
            },
            {
                "requirement_id": "target:115:apc:chemistry:compulsory",
                "source_reference": "official:handbook:115:p.12",
                "source_location": "PDF p.12 表二",
                "coverage_state": "PARTIAL",
                "evidence_state": "VERIFIED",
            },
        ),
        statistics={
            "total_graduation_credits": "128",
            "recognized_credits": "3",
            "effective_recognized_credits": "3",
            "unallocated_credits": "3",
            "shared_shadow_credits": "0",
            "credit_conservation": True,
            "by_bucket": {"required": "0", "elective": "3", "general_education": "0", "free": "0"},
            "requirement_status_counts": {"UNKNOWN": 2},
            "course_status_counts": {"PASS": 1, "IN_PROGRESS": 1},
            "completed": 1,
            "in_progress": 1,
            "unresolved": 0,
            "deficits": (
                {"requirement_id": "primary:113:earth:domain-elective", "name": "地生系專業選修", "deficit": "3", "status": "UNKNOWN"},
                {"requirement_id": "target:115:apc:chemistry:compulsory", "name": "物化系化學組必修", "deficit": "4", "status": "UNKNOWN"},
            ),
        },
        blockers=blockers or (
            "REQUIREMENT_DEFICIT:primary:113:earth:domain-elective",
            "APPLICATION:APPLICATION_FORMAL_APPROVAL_MISSING",
            "SEARCH_INCOMPLETE",
            "SEARCH_EXHAUSTED",
            "WAIVER_DECISION_REQUIRED",
            "RULE_CONTEXT:MANUAL_REVIEW",
            "CREDIT_CONSERVATION_FAILED",
            "attempt:113-1:MATH101:0",
        ),
        warnings=warnings or ("RULE_CONTEXT:MANUAL_REVIEW", "SEARCH_EXHAUSTED"),
        remediation_suggestions=remediation_suggestions or (
            "REQUIREMENT_DEFICIT:primary:113:earth:domain-elective",
            "APPLICATION:DOUBLE_MAJOR_NOT_APPROVED",
        ),
        non_credit_results=non_credit_results,
        subset_results=subset_results,
    )


class AdversarialForbiddenTokenScannerTests(unittest.TestCase):
    """Adversarially scan HTML, CSV, and PDF against forbidden internal debug tokens."""

    def test_full_adversarial_snapshot_zero_forbidden_tokens_in_html(self):
        """HTML representation must contain ZERO occurrences of any forbidden token."""
        snapshot = _build_adversarial_snapshot()
        html = render_snapshot(snapshot)

        matches = FORBIDDEN_TOKEN_REGEX.findall(html)
        self.assertEqual(
            matches,
            [],
            f"Forbidden tokens leaked in HTML: {matches}\nSample HTML context around leaks.",
        )

    def test_full_adversarial_snapshot_zero_forbidden_tokens_in_csv(self):
        """CSV representation must contain ZERO occurrences of any forbidden token."""
        snapshot = _build_adversarial_snapshot()
        rows, csv_text = _extract_csv_rows_and_text(build_student_allocation_csv(snapshot))

        matches = FORBIDDEN_TOKEN_REGEX.findall(csv_text)
        self.assertEqual(
            matches,
            [],
            f"Forbidden tokens leaked in CSV text: {matches}",
        )
        # Check every individual cell in every row
        for row_idx, row in enumerate(rows):
            for col_name, cell_val in row.items():
                cell_matches = FORBIDDEN_TOKEN_REGEX.findall(cell_val)
                self.assertEqual(
                    cell_matches,
                    [],
                    f"Forbidden tokens in row {row_idx} column '{col_name}': {cell_matches}",
                )

    def test_full_adversarial_snapshot_zero_forbidden_tokens_in_pdf(self):
        """PDF representation must contain ZERO occurrences of any forbidden token."""
        snapshot = _build_adversarial_snapshot()
        pdf_bytes = build_student_pdf(snapshot)
        pdf_text = _extract_pdf_text(pdf_bytes)

        matches = FORBIDDEN_TOKEN_REGEX.findall(pdf_text)
        self.assertEqual(
            matches,
            [],
            f"Forbidden tokens leaked in PDF: {matches}",
        )

    def test_diverse_application_codes_zero_leaks_across_all_media(self):
        """All variations of APPLICATION:* must be translated without leaking."""
        application_codes = (
            "APPLICATION:APPLICATION_FORMAL_APPROVAL_MISSING",
            "APPLICATION:DEPARTMENT_APPROVAL_MISSING",
            "APPLICATION:REGISTRAR_REGISTRATION_MISSING",
            "APPLICATION:FORMAL_QUALIFICATION_MISSING",
            "APPLICATION:APPLICATION_RESOLUTION_UNKNOWN",
            "APPLICATION:MINOR_APPLICATION_RESOLUTION_UNKNOWN",
            "APPLICATION:MINOR_QUALIFICATION_UNKNOWN",
            "APPLICATION:MINOR_QUALIFICATION_NOT_GRANTED",
            "APPLICATION:APPLICATION_STUDENT_STATUS_UNVERIFIED",
            "APPLICATION:APPLICATION_SELF_REPORT_UNVERIFIED",
            "APPLICATION:APPLICATION_EVENT_MISSING",
            "APPLICATION:UNIVERSITY_WINDOW_CLOSED",
            "APPLICATION:DEPARTMENT_WINDOW_CLOSED",
            "APPLICATION:ELIGIBILITY_UNMET",
            "APPLICATION:RULE_VERSION_UNRESOLVED",
            "APPLICATION:ACTIVITY_UNVERIFIED",
            "APPLICATION:UNKNOWN",
            "APPLICATION:INCOMPLETE",
            "APPLICATION:FAIL",
            "APPLICATION:PENDING",
            "APPLICATION:DOUBLE_MAJOR_NOT_APPROVED",
            "APPLICATION:MINOR_NOT_APPROVED",
            "APPLICATION:UNKNOWN_CUSTOM_SUBTYPE_999",
        )
        snapshot = _build_adversarial_snapshot(
            blockers=application_codes[:10],
            warnings=application_codes[10:18],
            remediation_suggestions=application_codes[18:],
        )

        html = render_snapshot(snapshot)
        _, csv_text = _extract_csv_rows_and_text(build_student_allocation_csv(snapshot))
        pdf_text = _extract_pdf_text(build_student_pdf(snapshot))

        for media_name, media_text in (("HTML", html), ("CSV", csv_text), ("PDF", pdf_text)):
            with self.subTest(media=media_name):
                matches = FORBIDDEN_TOKEN_REGEX.findall(media_text)
                self.assertEqual(matches, [], f"Forbidden token in {media_name}: {matches}")
                self.assertNotIn("APPLICATION:", media_text)

    def test_search_exhausted_and_incomplete_states_translated(self):
        """SEARCH_INCOMPLETE, SEARCH_EXHAUSTED, SEARCH_EXHAUSTED_AFTER_FEASIBLE_WITNESS."""
        search_codes = (
            "SEARCH_INCOMPLETE",
            "SEARCH_EXHAUSTED",
            "SEARCH_EXHAUSTED_AFTER_FEASIBLE_WITNESS",
            "SEARCH_EXHAUSTED_DEPTH_LIMIT",
        )
        snapshot = _build_adversarial_snapshot(
            blockers=search_codes,
            warnings=search_codes,
            remediation_suggestions=search_codes,
        )

        html = render_snapshot(snapshot)
        _, csv_text = _extract_csv_rows_and_text(build_student_allocation_csv(snapshot))
        pdf_text = _extract_pdf_text(build_student_pdf(snapshot))

        for media_name, media_text in (("HTML", html), ("CSV", csv_text), ("PDF", pdf_text)):
            with self.subTest(media=media_name):
                matches = FORBIDDEN_TOKEN_REGEX.findall(media_text)
                self.assertEqual(matches, [], f"Forbidden token in {media_name}: {matches}")
                self.assertNotIn("SEARCH_INCOMPLETE", media_text)
                self.assertNotIn("SEARCH_EXHAUSTED", media_text)
                self.assertIn("審核搜尋已達最大深度", media_text)

    def test_non_credit_and_subset_gates_with_internal_codes(self):
        """Non-credit gates with course codes 28030, 07140 and subset constraints."""
        non_credit = (
            {
                "requirement_id": "pe_orientation",
                "name": "28030",
                "kind": "SINGLE_COURSE",
                "status": "PASS",
                "required_count": 1,
                "completed_count": 1,
                "evidence": "VERIFIED",
                "coverage": "COMPLETE",
                "affects_credit_ledger": False,
                "blockers": ("ZERO_CREDIT_GATE_EVIDENCE_REQUIRED:pe_orientation",),
                "provenance": ({"source_reference": "handbook:113:earth:primary:p10"},),
            },
            {
                "requirement_id": "service_learning",
                "name": "07140",
                "kind": "SINGLE_COURSE",
                "status": "PASS",
                "required_count": 1,
                "completed_count": 1,
                "evidence": "VERIFIED",
                "coverage": "COMPLETE",
                "affects_credit_ledger": False,
            },
        )
        subsets = (
            {
                "constraint_id": "primary:free:science",
                "membership_id": "science_college",
                "name": "理學院自由學分下限",
                "status": "PASS",
                "required_credits": "3",
                "verified_credits": "3",
                "unknown_candidate_credits": "0",
                "source_reference": "official:free:p12",
            },
            {
                "constraint_id": "cs_beta_domain:115:network",
                "membership_id": "cs_beta_domain:115:network",
                "name": "",
                "status": "PASS",
                "required_credits": "0",
                "verified_credits": "3",
                "unknown_candidate_credits": "0",
                "source_reference": "official:cs:115:p124",
            },
        )
        snapshot = _build_adversarial_snapshot(
            non_credit_results=non_credit,
            subset_results=subsets,
        )

        html = render_snapshot(snapshot)
        _, csv_text = _extract_csv_rows_and_text(build_student_allocation_csv(snapshot))
        pdf_text = _extract_pdf_text(build_student_pdf(snapshot))

        for media_name, media_text in (("HTML", html), ("CSV", csv_text), ("PDF", pdf_text)):
            with self.subTest(media=media_name):
                matches = FORBIDDEN_TOKEN_REGEX.findall(media_text)
                self.assertEqual(matches, [], f"Forbidden token in {media_name}: {matches}")
                self.assertNotIn("handbook:113", media_text)


class CitationFormattingTests(unittest.TestCase):
    """Verify handbook and curriculum citation formatting."""

    def test_handbook_citation_exact_formats(self):
        """handbook:113:earth:... must format with exact spaces and Traditional Chinese terms."""
        cases = [
            (
                "handbook:113:earth:primary:earth_environment:domain-elective:p45:r0",
                "113 學年度地生系（地球環境組）學生手冊 第 45 頁 專業選修規定",
            ),
            (
                "handbook:113:earth:secondary:earth_environment:domain-elective:p45:r0",
                "113 學年度地生系雙主修/輔系（地球環境組）學生手冊 第 45 頁 專業選修規定",
            ),
            (
                "handbook:115:apc:target:chemistry:compulsory:p12:r1",
                "115 學年度物化系雙主修/輔系（化學組）學生手冊 第 12 頁 專業必修規定",
            ),
            (
                "official:handbook:114:p.10",
                "114 學年度學生手冊 第 10 頁 規定",
            ),
            (
                "primary:113:earth:earth_environment",
                "113 學年度地生系（地球環境組）主修課程綱要",
            ),
            (
                "target:115:apc:chemistry",
                "115 學年度物化系（化學組）雙主修課程綱要",
            ),
            (
                "minor:114:math",
                "114 學年度數學系輔系課程綱要",
            ),
        ]
        for raw_citation, expected in cases:
            with self.subTest(citation=raw_citation):
                formatted = format_handbook_citation(raw_citation)
                self.assertEqual(formatted, expected)

    def test_official_rules_preserved_for_contract(self):
        """Preserve official:pe:p5 and official:free:p12 required by export contracts."""
        self.assertEqual(format_handbook_citation("official:pe:p5"), "official:pe:p5")
        self.assertEqual(format_handbook_citation("official:free:p12"), "official:free:p12")


class ParametricBlockerAdviceTests(unittest.TestCase):
    """Verify translate_requirement_blocker provides valid amounts and Chinese names."""

    def test_requirement_deficit_with_context_amount_and_name(self):
        """REQUIREMENT_DEFICIT with known requirement context formats exact deficit credits."""
        req = {
            "requirement_id": "primary:113:earth:domain-elective",
            "name": "地生系專業選修",
            "deficit": "6",
        }
        advice = translate_requirement_blocker(
            "REQUIREMENT_DEFICIT:primary:113:earth:domain-elective",
            requirement=req,
        )
        self.assertEqual(advice, "地生系專業選修：尚缺 6 學分，請依系所規定選修。")

    def test_requirement_deficit_with_decimal_deficit(self):
        """Deficit with decimal value e.g. 4.5 credits."""
        req = {
            "requirement_id": "req-custom",
            "name": "跨領域選修",
            "deficit": "4.5",
        }
        advice = translate_requirement_blocker(
            "REQUIREMENT_DEFICIT:req-custom",
            requirement=req,
        )
        self.assertEqual(advice, "跨領域選修：尚缺 4.5 學分，請依系所規定選修。")

    def test_requirement_deficit_fallback_parsing(self):
        """When requirement is not in active map, fallback parses colon namespace into Chinese."""
        advice = translate_requirement_blocker("REQUIREMENT_DEFICIT:primary:113:earth:domain-elective")
        self.assertEqual(advice, "地生系專業選修：尚缺學分，請依系所規定選修。")

        target_advice = translate_requirement_blocker("REQUIREMENT_DEFICIT:target:115:apc:chemistry:compulsory")
        self.assertEqual(target_advice, "雙主修物化系化學組專業必修：尚缺學分，請依系所規定選修。")

    def test_other_requirement_blockers_translated(self):
        """Evidence unknown, coverage unknown, waiver decision required, zero credit gate."""
        cases = [
            (
                "REQUIREMENT_EVIDENCE_UNKNOWN:req-core",
                "系必修核心：尚有課程或採計條件待核對，請查看下方課程明細；不代表沒有修課。",
            ),
            (
                "REQUIREMENT_COVERAGE_UNKNOWN:req-core",
                "系必修核心：適用課程清單尚未完整，請向系所或教務處確認。",
            ),
            (
                "WAIVER_DECISION_REQUIRED:req-core",
                "系必修核心：免修或抵認尚待教務處或系所正式核准。",
            ),
            (
                "ZERO_CREDIT_GATE_EVIDENCE_REQUIRED:pe_orientation",
                "大學生活學習與輔導：非學分門檻尚待完成或缺少核准證明。",
            ),
            (
                "ZERO_CREDIT_GATE_EVIDENCE_REQUIRED:07140",
                "服務學習：非學分門檻尚待完成或缺少核准證明。",
            ),
        ]
        for blocker_code, expected in cases:
            with self.subTest(code=blocker_code):
                translated = translate_requirement_blocker(blocker_code)
                self.assertEqual(translated, expected)


class CleanStudentFacingTextFailsafeTests(unittest.TestCase):
    """Stress-test clean_student_facing_text as the ultimate defense-in-depth boundary."""

    def test_scrubber_replaces_embedded_debug_tokens(self):
        """Scrubber replaces tokens even when concatenated or embedded in sentences."""
        test_strings = [
            "審核提醒：REQUIREMENT_DEFICIT:primary:113:earth:domain-elective 請注意",
            "狀態為 APPLICATION:APPLICATION_FORMAL_APPROVAL_MISSING 需補件",
            "搜尋狀況：SEARCH_INCOMPLETE，採用最佳配置",
            "依據 handbook:113:earth:primary:earth_environment:domain-elective:p45:r0 之條文",
            "依據 official:handbook:114:p.10 辦理",
            "目前狀態 WAIVER_DECISION_REQUIRED 需人工審理",
            "核對版本 RULE_CONTEXT:MANUAL_REVIEW 請核算",
            "學分異常 CREDIT_CONSERVATION_FAILED 發生",
            "修課條目 attempt:113-1:MATH101:0 判定為通過",
            "主修課綱 primary:113:earth:earth_environment 需滿足",
            "雙主修課綱 target:115:apc:chemistry 需滿足",
        ]
        for text in test_strings:
            with self.subTest(text=text):
                cleaned = clean_student_facing_text(text)
                matches = FORBIDDEN_TOKEN_REGEX.findall(cleaned)
                self.assertEqual(matches, [], f"Leak in cleaned text: '{cleaned}' (original: '{text}')")


if __name__ == "__main__":
    unittest.main()
