name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git remote add hf https://u11310019:${HF_TOKEN}@huggingface.co/spaces/UTaipei-Student-Tools/Utaipei-credit-checker

          git push hf main --force
